os:
- Windows Server 2012 R2

version: 5.2.{build}

branches:
  only:
    - master

cache: c:\tools\vcpkg\installed\
# cache: c:\tools\vcpkg\installed\ -> appveyor.yml

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    PYTHON: "C:\\Miniconda36-x64"
    PYTHON_VERSION: "3.6"
    PYTHON_ARCH: "64"
    OPENVDB_ABI: 5
    OPENVDB_CORE_SHARED: ON
    OPENVDB_CORE_STATIC: OFF
    OPENVDB_UNITTESTS: OFF
    OPENVDB_DOCS: OFF
    OPENVDB_TOOLS: OFF
    OPENVDB_PYTHON: OFF
    OPENVDB_MAYA_PLUGIN: OFF
    OPENVDB_HOUDINI_PLUGIN: OFF
    CMAKE_GENERATOR: Visual Studio 14 2015 Win64
    VCPKG_DEFAULT_TRIPLET: x64-windows
    VCPKG_x64_SHARED_ROOT: C:/tools/vcpkg/installed/x64-windows
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14.0
    CONFIGURATION: Release

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PYTHON: "C:\\Miniconda36-x64"
    PYTHON_VERSION: "3.6"
    PYTHON_ARCH: "64"
    OPENVDB_ABI: 5
    # LINK 2019
    # OPENVDB_CORE_SHARED: ON
    # OPENVDB_CORE_STATIC: OFF
    OPENVDB_CORE_SHARED: OFF
    OPENVDB_CORE_STATIC: ON
    OPENVDB_UNITTESTS: OFF
    OPENVDB_DOCS: OFF
    OPENVDB_TOOLS: OFF
    OPENVDB_PYTHON: OFF
    OPENVDB_MAYA_PLUGIN: OFF
    OPENVDB_HOUDINI_PLUGIN: OFF
    CMAKE_GENERATOR: Visual Studio 15 2017 Win64
    VCPKG_DEFAULT_TRIPLET: x64-windows
    VCPKG_x64_SHARED_ROOT: C:/tools/vcpkg/installed/x64-windows
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14.1
    CONFIGURATION: Release

init:
  - cmd: echo "init"
install:
  - cmd: echo "install"

before_build:
  - cmd: cd C:\tools\vcpkg
  - cmd: vcpkg install glew glfw3 zlib blosc openexr tbb cppunit
  - cmd: vcpkg integrate install
  - cmd: set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%;%VCPKG_x64_SHARED_ROOT%

  - cmd: set BOOST_ROOT=C:\Libraries\boost_1_67_0
  - cmd: set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%;%BOOST_ROOT%

  - cmd: set PYTHON_ROOT = "C:\Python27-x64"
  - cmd: set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%;%PYTHON_ROOT%

# -DOPENVDB_SHARED=%OPENVDB_CORE_SHARED% -DOPENVDB_STATIC=%OPENVDB_CORE_STATIC%
build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -G"%CMAKE_GENERATOR%" -DCMAKE_CONFIGURATION_TYPES=%CONFIGURATION% -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DUSE_GLFW3=ON -DOPENVDB_BUILD_PYTHON_MODULE=%OPENVDB_PYTHON% -DOPENVDB_BUILD_UNITTESTS=%OPENVDB_UNITTESTS% -DOPENVDB_BUILD_DOCS=%OPENVDB_DOCS% -DOPENVDB_BUILD_TOOLS=%OPENVDB_TOOLS% -DCPPUNIT_LOCATION=%VCPKG_x64_SHARED_ROOT% -DOPENEXR_LOCATION=%VCPKG_x64_SHARED_ROOT% -DILMBASE_LOCATION=%VCPKG_x64_SHARED_ROOT% -DTBB_LOCATION=%VCPKG_x64_SHARED_ROOT% -DBLOSC_LOCATION=%VCPKG_x64_SHARED_ROOT% -DGLEW_LOCATION=%VCPKG_x64_SHARED_ROOT% -DGLFW3_LOCATION=%VCPKG_x64_SHARED_ROOT%
  - cmd: cmake --build . --config %CONFIGURATION% --target install


